spring:
  application:
    name: drugstores-on-duty
logging:
  level:
    root: ${env.drugstores.logging.level.root:ERROR}
    com.github.voragoth.drugstores: ${env.drugstores.logging.level.service:INFO}
    com.netflix.config.sources.URLConfigurationSource: ERROR
feign:
  hystrix:
    enabled: ${env.drugstores.feign.hystrix.enabled:true}
  client:
    config:
      default:
        loggerLevel: ${env.drugstores.feign.logging.level:NONE}
    drugstores-on-duty:
      connectTimeout: ${env.drugstores.feign.drugstores-on-duty.connect-timeout:10000}
      readTimeout: ${env.drugstores.feign.drugstores-on-duty.read-timeout:20000}
    admin-divisions:
      connectTimeout: ${env.drugstores.feign.admin-divisions.connect-timeout:10000}
      readTimeout: ${env.drugstores.feign.admin-divisions.read-timeout:20000}
drugstores:
  default-region: ${env.drugstores.default-region}
  feign:
    admin-divisions:
      base-url: ${env.admin-division.base-url}
      regions-path: ${env.admin-division.regions-path}
      communes-path: ${env.admin-division.communes-path}
    drugstores-on-duty:
      base-url: ${env.drugstores-on-duty.base-url}
      drugstores-by-region-path: ${env.drugstores-on-duty.drugstores-by-region-path}
      drugstores-on-duty-path: ${env.drugstores-on-duty.drugstores-on-duty-path}