spring:
  application:
    name: drugstores-on-duty
logging:
  level:
    root: ${env.drugstores.logging.level.root:ERROR}
    com.github.voragoth.drugstores: ${env.drugstores.logging.level.service:INFO}
    com.netflix.config.sources.URLConfigurationSource: ERROR
feign.client.config.default.loggerLevel: ${env.drugstores.logging.feign:NONE}
drugstores:
  default-region: ${env.drugstores.default-region}
  feign:
    admin-divisions:
      base-url: ${env.admin-division.base-url}
      regions-path: ${env.admin-division.regions-path}
      communes-path: ${env.admin-division.communes-path}
    drugstores-on-duty:
      base-url: ${env.drugstores-on-duty.base-url}
      drugstores-by-region-path: ${env.drugstores-on-duty.drugstores-by-region-path}